swagger: '2.0'
info:
  title: Configs API
  description: Configs API description
  version: '1.0.0'

host: localhost
basePath: /v1
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json

paths:
  /configs:
    get:
      tags:
        - Configs
      summary: Get Configs
      security:
        - Bearer: []
      responses:
        '200':
          description: Get Configs
          schema: 
            $ref: '#/definitions/Configs'

  /configs/{type}:
    get:
      tags:
        - Configs
      summary: Get Config by Type
      security:
        - Bearer: []
      parameters:
        - name: type
          in: path
          description: the config type
          required: true
          type: string
        - name: name
          in: query
          description: name of config type
          required: false
          type: string      
      responses:
        '200':
          description: Get Config by Type
          schema: 
            $ref: '#/definitions/Config'
    post:
      tags:
        - Configs
      summary: Create Config by Type
      security:
        - Bearer: []
      parameters:
        - name: type
          in: path
          description: the config type
          required: true
          type: string
        - name: body
          in: body
          description: the config payload
          required: true
          schema: 
            $ref: '#/definitions/Config'
      responses:
        '201':
          description: Create Config by Type
          schema:
            $ref: '#/definitions/Config'
    put:
      tags:
        - Configs
      summary: Update Config by Type
      security:
        - Bearer: []
      parameters:
        - name: type
          in: path
          description: the config type
          required: true
          type: string
        - name: body
          in: body
          description: the config payload
          required: true
          schema: 
            $ref: '#/definitions/Config'
      responses:
        '200':
          description: Update Config by Type
          schema:
            $ref: '#/definitions/Config'   
  /configs/{type}/authorization:
    post:
      tags:
        - Configs
      summary: Create Configs Authorization
      security:
        - Bearer: []
      parameters:
        - name: type
          in: path
          description: the config type
          required: true
          type: string
        - name: body
          in: body
          description: the authorization payload
          required: true
          schema: 
            $ref: '#/definitions/Authorization'          
      responses:
        '201':
          description: Create Configs Authorization
          schema: 
            $ref: '#/definitions/Authorization'
    put:
      tags:
        - Configs
      summary: Update Configs Authorization
      security:
        - Bearer: []
      parameters:
        - name: type
          in: path
          description: the config type
          required: true
          type: string
      responses:
        '200':
          description: Update Configs Authorization
          schema: 
            $ref: '#/definitions/Authorization'

definitions:
  Authorization:
    type: object
    properties:
      scopes:
        type: array
        items:
          type: string
      client_id:
        type: string
      client_secret:
        type: string
      description:
        type: string

  Configs:
    type: object
    properties:
      configs:
        type: array
        items:
          $ref: '#/definitions/Config'

  Config:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      config:
        type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
